version: "3.9"

volumes:
  local_superset_metadata_db: {}
  local_postgres_data: {}
  local_redis_data: {}
  
services:
  develop:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ecommerce_analytics
    container_name: ecommerce_analytics
    volumes:
      - ./.envs:/media/ecommerce_analytics/config
      - ./data:/media/ecommerce_analytics/data
      - ./logs:/media/ecommerce_analytics/logs
      - ./utils:/media/ecommerce_analytics/utils
      - ./examples:/media/ecommerce_analytics/examples
      - ./environment.yml:/media/ecommerce_analytics/environment.yml
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "tail -f /dev/null"
  db:
    image: postgres:14
    container_name: ecommerce_analytics_db
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - ./.envs/.postgres.env
    shm_size: '4gb'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    networks:
        - superset-net
  redis:
    image: redis
    restart: always
    volumes:
      - local_redis_data:/data
    networks:
    - superset-net

  superset:
    build: 
      context: .
      dockerfile: compose/superset/Dockerfile
    container_name: superset
    depends_on:
      - db
      - redis
      - metadata_db
    ports:
      - "8088:8088"
    env_file:
      - ./.envs/.superset.env
    environment:
      - MAPBOX_API_KEY = ${MAPBOX_API_KEY}
    volumes:
      - ./compose/superset/superset_config.py:/app/superset/superset_config.py
      - ./data/olist-dashboard.zip:/app/olist-dashboard.zip
    networks:
        - superset-net

  metadata_db:
      image: postgres:14
      container_name: metadata_db
      hostname: metadata_db
      env_file:
        - ./.envs/.superset.env
      volumes:
        - local_superset_metadata_db:/var/lib/postgresql/data
      ports:
        - "5435:5432"
      networks:
        - superset-net

networks:
  traefik-net:
  superset-net:
    driver: bridge