version: "3.9"
services:
  develop:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: ecommerce_analytics
    volumes:
      - ./config:/media/ecommerce_analytics/config
      - ./data:/media/ecommerce_analytics/data
      - ./database:/media/ecommerce_analytics/database
      - ./logs:/media/ecommerce_analytics/logs
      - ./utils:/media/ecommerce_analytics/utils
      - ./examples:/media/ecommerce_analytics/examples
      - ./environment.yml:/media/ecommerce_analytics/environment.yml
      - ./wait-for-it.sh:/media/ecommerce_analytics/wait-for-it.sh:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "tail -f /dev/null"
  db:
    image: postgres
    container_name: ecommerce_analytics_db
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    shm_size: '4gb'
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  superset:
    image: apache/superset
    container_name: superset
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8088:8088"
    environment:
      MAPBOX_API_KEY: pk.eyJ1IjoiYWxpbWhtemFkZWgiLCJhIjoiY2w1NnJyeTRyMTAxeDNnbDgydm02aDN1diJ9.OZ7kMqA6NgYAJ9_F9xNqxw
    volumes:
      - ./superset-data:/app/superset_home/
      - ./config/superset_config.py:/etc/superset/superset_config.py

volumes:
  db:
  redis: